### ISSUE TITLE
FullSizeRender.jpg bug (Image name/image path issue)

### ISSUE THREAD

**Issue by Namanjain12** [fluttercandies/flutter_wechat_assets_picker#555] opened 2024-02-28 10:10 UTC
**Describe the bug**
When we are selecting photos from gallery in iOS. It's randomly providing the path name ending with FullSizeRender.jpg. But it should be pick the actual path and actual name of the image.

**How to reproduce**
I am using below code
Line 1 : File? filed = await assetList[i].originFile;
Line 2 : String actualPath = filed.path.toString();
Line 3 : print(actualPath);

Result : /Library/Developer/CoreSimulator/Devices/8B4F62DB-32F6-4C1C-A0B7-111EB3A04251/data/Containers/Data/Application/8B795E3B-7708-47D7-9BB6-613CA3521FC5/tmp/.image/1708733115.890859_o_FullSizeRender.jpg

1. Click any photo from iPhone
2. Just Crop the image
3. Now, when you are trying to upload
4. Error occurred.

**Expected behavior**
It should pick the actual path of the image instead of "FullSizeRender.jpg"

- Device: iPhone only

**Comment by Namanjain12** [comment] 2024-02-28 10:23
I have an image(Image name : IMG_3818). If i pick the image path, it returns "Application/8B795E3B-7708-47D7-9BB6-613CA3521FC5/tmp/.image/1708733115.890859_o_FullSizeRender.jpg".

It should return with the ending of IMG_3818.HEIC. But it returns above path.

![simulator_screenshot_93F3F06F-A67F-4BF2-AF5B-0776DE78F75F](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/65751884/19180979-4335-4740-b8c8-98940092d265)

![simulator_screenshot_D69E60EA-2700-4AD5-8A83-ACF62B007DC4](https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/65751884/da6bbd78-7b7e-4604-a32a-4f74b57a68ee)

**Comment by Namanjain12** [comment] 2024-02-29 05:48
Any update, please ?

**Comment by Namanjain12** [comment] 2024-02-29 13:01
Please provide an update; a day has already passed.

**Comment by AlexV525** [comment] 2024-02-29 13:11
There could be more days. Open-source is not your paid business. And you didn't provide valid info, like versions and specified devices, the issue is not actionable at this moment. Also, you've already tried to bulling the repo by creating various duplicated issues without any new useful information, as a tip, this might lead to some unexpected results.

**Comment by AlexV525** [comment] 2024-03-03 07:54
Duplicate of https://github.com/fluttercandies/flutter_photo_manager/issues/976

**Closed by AlexV525** 2024-03-03 07:54 UTC
Labels: i: duplicate, i: fixed
