### ISSUE TITLE
[BUG] Error with the only video instagram picker

### ISSUE THREAD

**Issue by Mabel-BracketsLab** [fluttercandies/flutter_wechat_assets_picker#416] opened 2023-02-24 08:11 UTC
**Describe the bug**
In your demo, specifically in the instagram selector, if you configure that only videos are shown and only one video can be chosen at most. In the preview it does not change for the selected video, it stays in the default video.

**How to reproduce**
There is the instagram picker like your demo but configured to only show videos and select max 1 video.

1. With the code, launch the picker
2. Then select one video
3. You'll see that the preview doesn't change for the selected video.
4. Error occurred.

**Expected behavior**
When the user selects the video, it is displayed in the preview.

**Comment by AlexV525** [comment] 2023-02-24 08:29
Please provide a minimal code example that highlighted your changes rather than a bunch of code which is not helpful to determine what is the cause. cc @LeGoffMael

**Comment by Mabel-BracketsLab** [comment] 2023-02-24 08:33
Hello! The code of instagram picker is the same. The only change is the next code:

`
  late final DefaultAssetPickerProvider provider = DefaultAssetPickerProvider (
      maxAssets: 1,
      requestType: RequestType.video,
  );
`

**Comment by LeGoffMael** [comment] 2023-02-24 08:51
I can reproduce the issue, i will look into it.
It seems that the video preview is not updated well.

<video src="https://user-images.githubusercontent.com/22376981/221134237-5c6acaf5-5f49-4d41-b43e-01e903a3e0eb.mov" width="300" />

**Comment by Mabel-BracketsLab** [comment] 2023-02-24 08:54
Thank you! I'll wait.

**Comment by LeGoffMael** [comment] 2023-02-24 10:01
The issue seems to be coming from `VideoPageBuilder` @AlexV525.
When the `asset` param is updated the state doesn't rebuild.

Adding `didUpdateWidget` fix this issue, but iCloud videos causes an exception.

```dart
@override
void didUpdateWidget(covariant VideoPageBuilder oldWidget) {
  // update current page when index is updated
  if (widget.asset != oldWidget.asset) {
    _isInitializing = false;
    _isLocallyAvailable = false;
    hasErrorWhenInitializing = false;
  }
  super.didUpdateWidget(oldWidget);
}
```

**Comment by AlexV525** [comment] 2023-02-25 03:31
Verify if #417 resolves the issue.

**Comment by LeGoffMael** [comment] 2023-02-27 01:35
It seems overall better but i can still see 2 issues :

1. I am getting an exception while loading some videos, (i cannot find the pattern), in the video below it occurred on the first and last selected video. The error also occurs on master branch.
```
[log] Produced file: File: '/private/var/mobile/Containers/Data/Application/D2CDBC9B-5C4E-497E-8F1A-D699303D4C4E/tmp/.video/1675326660.619526_o_FullSizeRender.mov'.
PhotoManager info: PHAsset path = /private/var/mobile/Containers/Data/Application/D2CDBC9B-5C4E-497E-8F1A-D699303D4C4E/tmp/.video/1675326660.619526_IMG_3301.MOV
PhotoManager info: Locally available for path /private/var/mobile/Containers/Data/Application/D2CDBC9B-5C4E-497E-8F1A-D699303D4C4E/tmp/.video/1675326660.619526_IMG_3301.MOV: 0
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Media url is unavailable when the asset is not locally available., null, null, null)
#0      StandardMethodCodec.decodeEnvelope (message_codecs.dart:653)
#1      MethodChannel._invokeMethod (platform_channel.dart:315)
<asynchronous suspension>
#2      _VideoPageBuilderState.initializeVideoPlayerController (video_page_builder.dart:97)
<asynchronous suspension>
```

2. Video preview is not displayed after loading from iCloud, only the play button is shown, i had to to unselect and reselect the video again to be able to see the preview. Videos that are already locally available are shown normally (e.g.: 3rd selected video in the below video - at 10sec) 


<video src="https://user-images.githubusercontent.com/22376981/221450739-0fe70c48-e7c0-448a-a991-55c1dc666e66.mp4" width="300px" />

**Comment by AlexV525** [comment] 2023-03-01 14:02
PR has been updated, please verify the issue again.

**Comment by LeGoffMael** [comment] 2023-03-03 01:04
It seems that both issues remains, after iCloud download, the video preview is not shown and there is still the same exception on the same video.

**Comment by AlexV525** [comment] 2023-03-09 14:48
Sorry I haven't got time to investigate this recently due to the limited time, please do further digging about this if you're interested, thanks!

**Comment by RoyalCoder88** [comment] 2023-04-21 14:25
Hi can this feature will be fixed, it's a must to have option:( ...thanks in advance!

**Comment by AlexV525** [comment] 2023-05-01 03:26
> It seems that both issues remains: after iCloud download, the video preview is not shown and there is still the same exception on the same video.

Is this happening when using the default viewer?

**Closed** 2023-07-21 03:00 UTC
Labels: await triage, await investigate
