### ISSUE TITLE
[Feature] Optimization required: It is taking to long for the grid to show

### ISSUE THREAD

**Issue by yanivshaked** [fluttercandies/flutter_wechat_assets_picker#116] opened 2021-05-02 09:17 UTC
**Version information**
- Device: Android OnePlus 8T
- OS: Android 10
- Package Version: 5.2.1
- Flutter Version: 2.0.5

**Is your feature request related to a problem?**
Opening the picker, it is taking too long until the grid appears with the images.
If you compare the performance to other pickers in the market, this picker takes a long time to present the grid.

**Describe the solution you'd like**
I have tried to run some tests to focus on the performance bottle neck. I am not sure, but it appears that the generation of the thumbnail per image is taking quite some time:
```
      final List<int> _thumbSize = thumbSize!;
      final Stopwatch sw = Stopwatch()..start();
      data = await key.entity.thumbDataWithSize(_thumbSize[0], _thumbSize[1]);
      print('thumbDataWithSize ${sw.elapsedMilliseconds}');
```

output:
```
I/flutter (23576): thumbDataWithSize 250
I/flutter (23576): thumbDataWithSize 239
I/flutter (23576): thumbDataWithSize 236
I/flutter (23576): thumbDataWithSize 233
I/flutter (23576): thumbDataWithSize 230
I/flutter (23576): thumbDataWithSize 227
I/flutter (23576): thumbDataWithSize 224
I/flutter (23576): thumbDataWithSize 220
I/flutter (23576): thumbDataWithSize 217
I/flutter (23576): thumbDataWithSize 213
I/flutter (23576): thumbDataWithSize 210
I/flutter (23576): thumbDataWithSize 206
I/flutter (23576): thumbDataWithSize 193
I/flutter (23576): thumbDataWithSize 190
I/flutter (23576): thumbDataWithSize 200
```

Note:
There is a bug in the "Custom Image Preview thumb size". It is not actually working - the thumb size is lost in the way. I will submit a PR to fix it (the bug is NOT in the example code but in the plugin itself).

**Describe alternatives you've considered**
- Tried reducing the image preview thumb size (after locally fixing the bug) - it helps, but not too much
- Tried reducing the routeDuration and other durations in code - didn't help
- Tried replacing default SortPathDelegate.common with SortPathDelegate.empty.empty (which does nothing), almost no change

**Several solutions which should be inspected**
- Check for PhotoManager preload thumb feature: [PhotoManager  PreloadThumb](https://pub.dev/packages/photo_manager#preload-thumb)
- Don't wait for all images thumb to be ready, display each when ready (does it work like that now?)
- Using the image itself instead of generating a thumbnail per image (probably not a good idea, but should be tested)

**Comment by AlexV525** [comment] 2021-05-02 15:44
> * Check for PhotoManager preload thumb feature: [PhotoManager  PreloadThumb](https://pub.dev/packages/photo_manager#preload-thumb)

Seems no improvement for me. The method requires you to throw assets into it, then you'll back to the very start of the issue which is the duration when getting assets list.

> * Don't wait for all images thumb to be ready, display each when ready (does it work like that now?)

Yes this is how it works currently. Load assets list, layout the grid, and items take care of the thumbnail themselves.

> * Using the image itself instead of generating a thumbnail per image (probably not a good idea, but should be tested)

IMO there's no need for testing. You can directly see their difference between the grid and the preview.

**Comment by yanivshaked** [comment] 2021-05-02 19:27
Do you have any other suggestion on how to optimize the grid loading?

**Comment by AlexV525** [comment] 2021-05-03 04:56
Not really. This might requires more enhancements from the `photo_manager` plugin. I'll discuss with @CaiJingLong offline later.

**Comment by yanivshaked** [comment] 2021-05-03 06:18
Thanks!

**Comment by zmhbh** [comment] 2021-05-29 01:12
I had the same issue as well.

**Comment by Letalus** [comment] 2021-07-02 08:48
i just wanted to also state, that some of my alpha tester, who have android devices, also complaint, that the loading time for the assets within the grid, is really slow. Apparently this problem is not really a big problem for iOS but it is was Android. If I can help somehow, please let me know and I can review the necessary android code to adjust it. Maybe one possibility would be to give the grid a stream of thumbnails instead of all images at once, to reduce the loading time.

Kind regards,
Chris

**Comment by AlexV525** [comment] 2021-07-02 09:06
> Apparently this problem is not really a big problem for iOS but it is was Android.

Actually we heard more complaint about this issue on iOS. But no matter which platforms are suffering this problem, we should definitely discuss this in the `photo_manager` repo.

I'll give some detail about the laggy part which the picker mainly suffered.

## Grid is always spinning

https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/77d86b5b45575744cd245a9292b7276acaab4bc8/lib/src/provider/asset_picker_provider.dart#L260-L261

The reason why the grid spins too long is caused by these methods, and they must be called in proper sequence. Anyone who wants to test how long these methods been taken, can place a `Stopwatch` here. AFAIK, low performance devices, devices that have more than thousands of entities, could both suffered from this.

## Thumbnails are slow with rendering

Thumbnails are provided by some native dependencies, e.g. Glide on Android, which requires a generate process when reaching them. Then they'll be copied in the Flutter's channel pipeline. This is how copies were transferred under the Android platform:

MediaStore -> `Uri` -> `Bitmap` -> `ByteArray` => Platform Channel => `Uint8List` -> `resolve` by `ImageProvider`.

Too many copies required to generate during this process, which means some laggy were produced by the architecture of channels.

However, they can be some solutions to solve this, but they're still under investigation by Flutter team. See https://discord.com/channels/608014603317936148/846507907876257822/850072476402450433 as we've discussed this few weeks ago.

**Comment by chriscdn** [comment] 2021-11-06 13:07
Has anyone found a solution?  The asset picker is functionally great, but it takes almost 10s on my iPhone SE (in release mode) for photos to start showing.

**Comment by matthiasn** [comment] 2022-01-24 14:29
Same here, like 10 seconds on an iPhone 12 Pro.

**Comment by AlexV525** [comment] 2022-02-23 13:17
If anyone still facing the same issue like this, or https://github.com/fluttercandies/flutter_photo_manager/issues/711, please help us by running the latest example of `photo_manager`, then filtering log as https://github.com/fluttercandies/flutter_photo_manager/issues/711#issuecomment-1048428521 suggested.

**Comment by AlexV525** [comment] 2022-03-07 03:38
We've shipped the 7.0.0 version which brought a bunch of improvements from the photo_manager 2.0.0 version.
If anyone is still facing the obvious performance/duration issues, contact me by submitting new issues in the [photo_manager's repo](https://github.com/fluttercandies/flutter_photo_manager).

Closing since we have few samples to solid reproduce this issue.

**Closed by AlexV525** 2022-03-07 03:38 UTC
Labels: e: goal, e: performance, await investigate, r: photo_manager, b: flutter, i: postpone, e: PR welcomed

**Comment by kartik1225** [comment] 2022-05-28 07:43
I reproduce this issue in google `pixel 4a`  `android 12`.
When I filter only videos that time grid is taking too long (7s - 10s) to load initially.
Once everything is cached it works as intended.

So in summary if we clear the data and filter only videos that time I am able to reproduce this bug.

**Comment by AlexV525** [comment] 2022-06-25 08:51
> So in summary if we clear the data and filter only videos that time I am able to reproduce this bug.

@kartik1225 If it's able to reproduce, please file issues against `photo_manager` and we'll take further investigations.
